### ISSUE TITLE
pong.sh fail

### ISSUE THREAD

**Issue by Sohojoe** [osh/kerlym#4]
pong does not converge on default settings

I tried DQN & DDQN - ran both for 55,000 Episodes and both fail to converge

DQN - kerlym -e Pong-v0 -n simple_cnn -t 1 -P -f 200 -u 250 -o 0.5 -D 0 -a dqn -S 1 -i https://gym.openai.com/evaluations/eval_4M7KAHHnSFKmw4cuhkTBkg
![kerlym -e pong-v0 -n simple_cnn -t 1 -p -f 200 -u 250 -o 0 5 -d 0 -a dqn -s 1 -i](https://cloud.githubusercontent.com/assets/4400544/15994266/6e7bca10-30b4-11e6-9f7b-b1d45f215b2e.png)

DDQN - kerlym -e Pong-v0 -n simple_cnn -t 1 -P -f 200 -u 250 -o 0.5 -D 0 -a ddqn -S 1 -i https://gym.openai.com/evaluations/eval_zTcrIwwhRK26Zung4mLlJA
![kerlym -e pong-v0 -n simple_cnn -t 1 -p -f 200 -u 250 -o 0 5 -d 0 -a ddqn -s 1 -i](https://cloud.githubusercontent.com/assets/4400544/15994260/520b5e4a-30b4-11e6-9f91-fa57aa6b034a.png)

**Comment by osh** [comment]
this is a work in progress, 
still working on tuning hyper-parameters and vetting the implementation against Atari games
your assistance in testing, debugging and improving is appreciated 
it should be noted also that in the original deepmind DQN paper, it plays for 38 days over 50million+ frames (since we play a max of 200 frames per game, this is 250k+ episodes vs the 55k here)

**Comment by osh** [comment]
give this a try on the latest branch,
I've done a lot of refactoring!

**Comment by Sohojoe** [comment]
great - I will check out the latest code

**Comment by danijar** [comment]
@Sohojoe Does it work now?
