### ISSUE TITLE
Should there be target networks for the A3C?

### ISSUE THREAD

**Issue by danijar** [osh/kerlym#7]
In your A3C implementation, you create [shared target networks](https://github.com/osh/kerlym/blob/master/kerlym/a3c/a3c.py#L91) to be synchronized with the learned network every some time steps (to stabilize training). I wonder if this is just your experiment because [in the paper](https://arxiv.org/pdf/1602.01783v2.pdf), I did not find any mentions of target networks for the A3C. Also, it's not in the pseudo code for A3C, only in the pseudo codes for one-step and n-step Q-learning. Thanks for your clarification!

**Comment by osh** [comment]
this is for sure a work in progress --- please note that caveat!
I probably should have it on a development branch instead so that is clear --- 

in the paper they describe thread specific weights theta' and theta'_v, and global weights theta and theta_v.   The hope was simply to use the "target" policy network (just a network with parameters theta and theta_v) as the global weight model store in a similar way to what DDQN impl was doing  -- 

Granted weights could be shared without the actual global weight model existing.   Target is probably a confusing word to use here --- was really just a holdover from DDQN code -

**Comment by osh** [comment]
this has been rewritten and is no longer relevent

**Comment by danijar** [comment]
Cool, thanks for your answer and keep up the work.

**Comment by MarkNader** [comment]
but in the paper they said two controversial statements :- 
1- they made an update every 5 actions for weights
2- they made an update every 40000 frames to a shared target network
How is the target is used the same as our policy network then? because certainly 5 actions dont correspond to 40000 frames
